# Generated by Django 5.0.7 on 2025-09-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('demographics', models.JSONField()),
                ('observations', models.JSONField()),
                ('note_panel_data', models.JSONField()),
                ('case_details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidx', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('original_name', models.TextField()),
                ('med_route', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=100, unique=True)),
                ('data_layout', models.JSONField()),
                ('variable_details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_data', models.JSONField()),
                ('y_axis_ranges', models.JSONField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.case')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study'),
        ),
        migrations.AddField(
            model_name='case',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study'),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('study', 'medidx')},
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('study', 'case_id')},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('cases_assigned', models.JSONField()),
                ('cases_completed', models.JSONField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study')),
            ],
            options={
                'unique_together': {('study', 'user_id')},
            },
        ),
    ]
