# Generated by Django 5.0.7 on 2025-09-24 19:41

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=100)),
                ('demographics', models.JSONField()),
                ('observations', models.JSONField()),
                ('note_panel_data', models.JSONField()),
                ('case_details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medidx', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('original_name', models.TextField()),
                ('med_route', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CaseMedication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('med_data', models.JSONField()),
                ('y_axis_ranges', models.JSONField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.case')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('study_id', models.CharField(max_length=100, unique=True)),
                ('data_layout', models.JSONField()),
                ('variable_details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['study_id'], name='SEMRinterfa_study_i_1c6a28_idx')],
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study'),
        ),
        migrations.CreateModel(
            name='CaseSelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('case_id', models.CharField(max_length=100)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='Legacy user identifier', max_length=100, unique=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('cases_assigned', models.JSONField(default=list, help_text='List of assigned case IDs')),
                ('cases_completed', models.JSONField(default=list, help_text='List of completed case IDs')),
                ('username', models.CharField(default='', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StoredResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('case_id', models.CharField(max_length=100)),
                ('selected_items', models.JSONField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study')),
            ],
            options={
                'indexes': [models.Index(fields=['study', 'user_id', 'case_id'], name='SEMRinterfa_study_i_1bd8f5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['study', 'medidx'], name='SEMRinterfa_study_i_30a7fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('study', 'medidx')},
        ),
        migrations.AddIndex(
            model_name='caseselection',
            index=models.Index(fields=['study', 'user_id', 'case_id'], name='SEMRinterfa_study_i_eac49d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseselection',
            unique_together={('study', 'user_id', 'case_id')},
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['study', 'case_id'], name='SEMRinterfa_study_i_577337_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('study', 'case_id')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['study', 'user_id'], name='SEMRinterfa_study_i_5df189_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='SEMRinterfa_usernam_c87b8d_idx'),
        ),
    ]
