# Generated by Django 5.0.7 on 2025-09-24 20:26

import SEMRinterface.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SEMRinterface", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", SEMRinterface.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                verbose_name="username",
            ),
        ),
    ]
