# Generated by Django 5.0.7 on 2025-09-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEMRinterface', '0002_storedresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('case_id', models.CharField(max_length=100)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEMRinterface.study')),
            ],
            options={
                'unique_together': {('study', 'user_id', 'case_id')},
            },
        ),
    ]
