# Generated by Django 5.0.7 on 2025-09-24 19:07

from django.db import migrations, models
from django.contrib.auth.hashers import make_password
import django.contrib.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('SEMRinterface', '0003_caseselection'),
    ]

    operations = [
        # Add AbstractUser fields to existing User model
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=make_password('password123'), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),

        # Data migration to populate username from user_id
        migrations.RunSQL(
            "UPDATE SEMRinterface_user SET username = user_id WHERE username = ''",
            reverse_sql="UPDATE SEMRinterface_user SET user_id = username WHERE user_id = ''"
        ),

        # Make username unique and required
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),

        # Update the Meta options to inherit from AbstractUser
        migrations.AlterModelOptions(
            name='user',
            options={'indexes': [('study', 'user_id'), ('username',)]},
        ),

        # Create permissions and groups tables if they don't exist
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS auth_group (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(150) NOT NULL UNIQUE
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS auth_group;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS auth_permission (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(255) NOT NULL,
                content_type_id INTEGER NOT NULL,
                codename VARCHAR(100) NOT NULL,
                UNIQUE(content_type_id, codename)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS auth_permission;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS auth_user_groups (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL REFERENCES SEMRinterface_user(id),
                group_id INTEGER NOT NULL REFERENCES auth_group(id),
                UNIQUE(user_id, group_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS auth_user_groups;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS auth_user_user_permissions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL REFERENCES SEMRinterface_user(id),
                permission_id INTEGER NOT NULL REFERENCES auth_permission(id),
                UNIQUE(user_id, permission_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS auth_user_user_permissions;"
        ),
    ]
